* 皇甫诞君碑

** 1
随柱国左光禄大夫弘义明公皇甫府君之碑

银青光禄大夫行太子左庶子上柱国黎阳县开国公于制宁制 　　

夫素秋肃煞，劲草标

** 2
於疾风；叔世艰虞，忠臣彰於赴难。衔须授命，结缨殉国，英声焕乎记
牒，徽烈著於旌常，岂若衅起萧墙，祸生蕃翰，强逾七国，势重三监，其有蹈水火而不辞，
临锋刃而莫

** 3
顾，激清风於后叶，抗名节於当时者，见之弘义明公矣。

君讳诞，字玄宪，安定朝那人也。昔立效长丘，树绩东郡，太尉裂壤於槐里，司徒胙土於而
彡门，是以车服旌其器能，

** 4

茅社表其勋德，铭功卫鼎，腾美晋锺，盛族冠於国高，华宗迈於
栾却，备在史牒，可略言焉。

曾祖重华，使持节龙骧将军梁州剌史。 润木晖山，方重价於赵璧；媚川照阙，曜

** 5

奇采於随珠。

祖和，雍州赞治，赠使持节散骑常侍车骑大将军仪同三司胶、泾二州刺史。高衢将骋，遽夭
追风之足；扶摇始搏，早坠垂天之羽。

父，使持节骠骑大将军

** 6

开府仪同三司随州刺史长乐恭侯。横剑┕互，威重冠军；析瑞蕃条，
声高渤海。公量包申伯，禀嵩山之秀气；材兼萧相，降昴纬之淑精。据德依仁，居贞体道。
含章表质，讵 

** 7

待变於朱蓝；恭孝为基，宁取训於桥梓。锋犀象，百练挺於昆吾；翼掩鸳鸿，九万奋於溟
海。博韬骨产，文瞻卿云，孝穷温情之方，忠尽匡救之道。同何充之器局，被重晋


** 8

君；类荀攸之宏图，见知魏主。斯故冗罗众艺，囊括群英者也。起家除周毕王府长史，荣
名蕃牧，则位重首寮；ㄚ服睢阳，则誉光上客。既而苍精委驭，炎运启图，作贰边服，

** 9

实资
令望，授广州长史。悦近来远，变轻讠少於雕题；伐叛怀柔，渐淳化於缓耳。蜀王地处维城，
寄深磐石，建玉垒，作镇铜梁，妙择奇才，以为僚佐，授公益州总管府司法。


** 10

昔梁孝开国，
首辟邹阳，燕昭建邦，肇徵郭隗。故得驰令问於碣馆，播芳猷於平台，以古方今，彼此一也。
寻除尚书比部侍郎，转刑部侍郎。步紫庭，光映朝列；折旋丹地，


** 11

誉重周行。俄迁治书侍
御史。弹违纠慝，时绝权豪；霜简直绳，俗寝贪竞。随文帝求衣待旦，志在恤刑，咒网泣辜，
情存缓狱。授大理少卿。公巨细必察，同张季之听理；宽猛

** 12

相济，比于公之无冤。但礼闱务
殷，枢辖寄重，允膺此职，实难其人。授尚书右丞，洞明政术，深晓治方，臧否自分，条目
咸理。丁母忧去职。哀恸里闾，邻人为之罢社；悲感衢

** 13

路，行客以之辍歌。孝德则师范彝伦，
精诚则贯微幽显，虽高曾之至性，何以加焉。寻诏夺情，复其旧任。于时山东之地，俗升民
浇，虽预编民，未行声教。诏公持节为河


** 14

北河南道安抚大使，仍赐米五百石、绢五百匹。公
轩布政，美冠皇华之篇；拥节观风，荣甚绣衣之使。事讫反命，授尚书左丞。然并州地处
参墟，城临晋水，作固同於西

** 15

蜀，设险类於东秦，实山河之要冲，信蕃服之襟带。授公并州
总管府司马，加仪同三司。公赞务大邦，声名藉甚，精民感化，黠吏畏威。属文帝剑玺空留，
銮跸莫反，杨谅率


** 16

太原之甲，拥河朔之兵。方叔段之作乱京城，同州吁之扌延祸濮上，虽无
当璧之地，乃怀夺冠不之心。公备说安危，具陈逆顺，翻纳魏勃之荣，反被王悍之灾。仁寿
四年九月，

** 17

溘从运往，春秋五十有一。万机起歼良之叹，百辟兴丧予之悲，切孔氏之山颓，
痛杨君之栋折。赠柱国、左光禄大夫，封弘义郡公，食邑五千户，谥曰明公，礼也。丧事所
须，


** 18

随由资给，赐帛五千段，粟三千石。惟公温润成性，夙表白虹之珍；黼黻为文，幼挺雕
龙之采。行已穷於六本，蕴德包於四科，延阁曲台之奇书，鸿都石渠之秘说，莫不寻

** 19

其枝叶，
践其奥隅。譬越箭达犀，馀之以括羽；楚金切玉，加之以磨龙。救乏同於指菌，亲识待其
举火，进贤方於推毂，知已俟以弹冠。存信舍原，黄金贱於然诺；忘身殉难，

** 20

性命轻於鸿毛。
齐大小於冲襟，混宠辱於灵府，可谓楷模雅俗，冠冕时雄者也。方当亮采泰阶，参综机务，
岂谓世逢多故，运属道消，未展经邦之谋，奄锺非命之酷。世子

** 21

民部尚书上柱国滑国公无逸，以为邢山之下，莫识祭仲之坟；平陵之东，谁知子孟之墓。乃
雕戈勒石，腾实飞声，树之康衢，永表芳烈。庶葛亮之陇，锺庄禁之以樵苏；贾


** 22

逵之碑，魏君叹之以不朽。

乃为铭曰：

殷后华宗，名卿胄系。人物代德，衣冠重世。逢时翼主，膺期佐帝。运荣经纶，执钧匡济。
门承积庆，世挺伟人。夜光愧宝，朝采惭珍。

** 23

云中比陆，日下方荀。抑扬元辅，参赞机钧。
玉叶东封，贰图北启。伏奏青蒲，曳裾朱邸。名驰碣石，声高建礼。珥笔宪台，握兰文陛。
分星裂士，建侯开国。辅藉正人，相资懿德。

** 24


中台辍务，晋阳就职。望重府朝，誉闻宸极。
乱阶蔓草，灾庄剪桐。成师构难，太叔兴戎。建德效节，夷吾尽忠。命屯道著，身殁名隆。
牛亭始卜，马犭葛初封。翠碑刻凤，丹旆图龙。

** 25


烟横古树，云镇乔松。敬铭盛德，永播笙镛。
案：此碑据北宋拓全文录。
